/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupDemoRouteImport } from './routes/setup-demo'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostIndexRouteImport } from './routes/host.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostsSlugRouteImport } from './routes/hosts.$slug'
import { Route as HostNewRouteImport } from './routes/host.new'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as HostSlugReviewRouteImport } from './routes/host.$slug.review'
import { Route as HostSlugMembersRouteImport } from './routes/host.$slug.members'
import { Route as HostSlugEditRouteImport } from './routes/host.$slug.edit'
import { Route as HostSlugDashboardRouteImport } from './routes/host.$slug.dashboard'
import { Route as HostSlugEventsNewRouteImport } from './routes/host.$slug.events.new'
import { Route as HostSlugEventsIdEditRouteImport } from './routes/host.$slug.events.$id.edit'
import { Route as HostSlugEventsIdCheckinRouteImport } from './routes/host.$slug.events.$id.checkin'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupDemoRoute = SetupDemoRouteImport.update({
  id: '/setup-demo',
  path: '/setup-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/host/',
  path: '/host/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsSlugRoute = HostsSlugRouteImport.update({
  id: '/hosts/$slug',
  path: '/hosts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HostNewRoute = HostNewRouteImport.update({
  id: '/host/new',
  path: '/host/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugReviewRoute = HostSlugReviewRouteImport.update({
  id: '/host/$slug/review',
  path: '/host/$slug/review',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugMembersRoute = HostSlugMembersRouteImport.update({
  id: '/host/$slug/members',
  path: '/host/$slug/members',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugEditRoute = HostSlugEditRouteImport.update({
  id: '/host/$slug/edit',
  path: '/host/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugDashboardRoute = HostSlugDashboardRouteImport.update({
  id: '/host/$slug/dashboard',
  path: '/host/$slug/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugEventsNewRoute = HostSlugEventsNewRouteImport.update({
  id: '/host/$slug/events/new',
  path: '/host/$slug/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugEventsIdEditRoute = HostSlugEventsIdEditRouteImport.update({
  id: '/host/$slug/events/$id/edit',
  path: '/host/$slug/events/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugEventsIdCheckinRoute = HostSlugEventsIdCheckinRouteImport.update({
  id: '/host/$slug/events/$id/checkin',
  path: '/host/$slug/events/$id/checkin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/setup-demo': typeof SetupDemoRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/host/new': typeof HostNewRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/': typeof HostIndexRoute
  '/host/$slug/dashboard': typeof HostSlugDashboardRoute
  '/host/$slug/edit': typeof HostSlugEditRoute
  '/host/$slug/members': typeof HostSlugMembersRoute
  '/host/$slug/review': typeof HostSlugReviewRoute
  '/host/$slug/events/new': typeof HostSlugEventsNewRoute
  '/host/$slug/events/$id/checkin': typeof HostSlugEventsIdCheckinRoute
  '/host/$slug/events/$id/edit': typeof HostSlugEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/setup-demo': typeof SetupDemoRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/host/new': typeof HostNewRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host': typeof HostIndexRoute
  '/host/$slug/dashboard': typeof HostSlugDashboardRoute
  '/host/$slug/edit': typeof HostSlugEditRoute
  '/host/$slug/members': typeof HostSlugMembersRoute
  '/host/$slug/review': typeof HostSlugReviewRoute
  '/host/$slug/events/new': typeof HostSlugEventsNewRoute
  '/host/$slug/events/$id/checkin': typeof HostSlugEventsIdCheckinRoute
  '/host/$slug/events/$id/edit': typeof HostSlugEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/setup-demo': typeof SetupDemoRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/host/new': typeof HostNewRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/': typeof HostIndexRoute
  '/host/$slug/dashboard': typeof HostSlugDashboardRoute
  '/host/$slug/edit': typeof HostSlugEditRoute
  '/host/$slug/members': typeof HostSlugMembersRoute
  '/host/$slug/review': typeof HostSlugReviewRoute
  '/host/$slug/events/new': typeof HostSlugEventsNewRoute
  '/host/$slug/events/$id/checkin': typeof HostSlugEventsIdCheckinRoute
  '/host/$slug/events/$id/edit': typeof HostSlugEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/my-events'
    | '/profile'
    | '/review'
    | '/setup-demo'
    | '/signup'
    | '/tickets'
    | '/events/$slug'
    | '/host/new'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/host/'
    | '/host/$slug/dashboard'
    | '/host/$slug/edit'
    | '/host/$slug/members'
    | '/host/$slug/review'
    | '/host/$slug/events/new'
    | '/host/$slug/events/$id/checkin'
    | '/host/$slug/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/my-events'
    | '/profile'
    | '/review'
    | '/setup-demo'
    | '/signup'
    | '/tickets'
    | '/events/$slug'
    | '/host/new'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/host'
    | '/host/$slug/dashboard'
    | '/host/$slug/edit'
    | '/host/$slug/members'
    | '/host/$slug/review'
    | '/host/$slug/events/new'
    | '/host/$slug/events/$id/checkin'
    | '/host/$slug/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/my-events'
    | '/profile'
    | '/review'
    | '/setup-demo'
    | '/signup'
    | '/tickets'
    | '/events/$slug'
    | '/host/new'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/host/'
    | '/host/$slug/dashboard'
    | '/host/$slug/edit'
    | '/host/$slug/members'
    | '/host/$slug/review'
    | '/host/$slug/events/new'
    | '/host/$slug/events/$id/checkin'
    | '/host/$slug/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MyEventsRoute: typeof MyEventsRoute
  ProfileRoute: typeof ProfileRoute
  ReviewRoute: typeof ReviewRoute
  SetupDemoRoute: typeof SetupDemoRoute
  SignupRoute: typeof SignupRoute
  TicketsRoute: typeof TicketsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  HostNewRoute: typeof HostNewRoute
  HostsSlugRoute: typeof HostsSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  HostIndexRoute: typeof HostIndexRoute
  HostSlugDashboardRoute: typeof HostSlugDashboardRoute
  HostSlugEditRoute: typeof HostSlugEditRoute
  HostSlugMembersRoute: typeof HostSlugMembersRoute
  HostSlugReviewRoute: typeof HostSlugReviewRoute
  HostSlugEventsNewRoute: typeof HostSlugEventsNewRoute
  HostSlugEventsIdCheckinRoute: typeof HostSlugEventsIdCheckinRoute
  HostSlugEventsIdEditRoute: typeof HostSlugEventsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-demo': {
      id: '/setup-demo'
      path: '/setup-demo'
      fullPath: '/setup-demo'
      preLoaderRoute: typeof SetupDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/': {
      id: '/host/'
      path: '/host'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$slug': {
      id: '/hosts/$slug'
      path: '/hosts/$slug'
      fullPath: '/hosts/$slug'
      preLoaderRoute: typeof HostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/new': {
      id: '/host/new'
      path: '/host/new'
      fullPath: '/host/new'
      preLoaderRoute: typeof HostNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/review': {
      id: '/host/$slug/review'
      path: '/host/$slug/review'
      fullPath: '/host/$slug/review'
      preLoaderRoute: typeof HostSlugReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/members': {
      id: '/host/$slug/members'
      path: '/host/$slug/members'
      fullPath: '/host/$slug/members'
      preLoaderRoute: typeof HostSlugMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/edit': {
      id: '/host/$slug/edit'
      path: '/host/$slug/edit'
      fullPath: '/host/$slug/edit'
      preLoaderRoute: typeof HostSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/dashboard': {
      id: '/host/$slug/dashboard'
      path: '/host/$slug/dashboard'
      fullPath: '/host/$slug/dashboard'
      preLoaderRoute: typeof HostSlugDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/events/new': {
      id: '/host/$slug/events/new'
      path: '/host/$slug/events/new'
      fullPath: '/host/$slug/events/new'
      preLoaderRoute: typeof HostSlugEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/events/$id/edit': {
      id: '/host/$slug/events/$id/edit'
      path: '/host/$slug/events/$id/edit'
      fullPath: '/host/$slug/events/$id/edit'
      preLoaderRoute: typeof HostSlugEventsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/events/$id/checkin': {
      id: '/host/$slug/events/$id/checkin'
      path: '/host/$slug/events/$id/checkin'
      fullPath: '/host/$slug/events/$id/checkin'
      preLoaderRoute: typeof HostSlugEventsIdCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MyEventsRoute: MyEventsRoute,
  ProfileRoute: ProfileRoute,
  ReviewRoute: ReviewRoute,
  SetupDemoRoute: SetupDemoRoute,
  SignupRoute: SignupRoute,
  TicketsRoute: TicketsRoute,
  EventsSlugRoute: EventsSlugRoute,
  HostNewRoute: HostNewRoute,
  HostsSlugRoute: HostsSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  HostIndexRoute: HostIndexRoute,
  HostSlugDashboardRoute: HostSlugDashboardRoute,
  HostSlugEditRoute: HostSlugEditRoute,
  HostSlugMembersRoute: HostSlugMembersRoute,
  HostSlugReviewRoute: HostSlugReviewRoute,
  HostSlugEventsNewRoute: HostSlugEventsNewRoute,
  HostSlugEventsIdCheckinRoute: HostSlugEventsIdCheckinRoute,
  HostSlugEventsIdEditRoute: HostSlugEventsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
